version: 2

project_name: sbomer
before:
  hooks:
    - go mod tidy
builds:
  - env: [CGO_ENABLED=0]
    binary: sbomer
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    id: "sbomer"
    dir: .
    main: cmd/sbomer/main.go
  - env: [CGO_ENABLED=0]
    binary: fetcher
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    id: "fetcher"
    dir: .
    main: cmd/fetcher/main.go

archives:
  - id: sbomer-archive
    format: tar.gz
    files:
      - none*
    ids:
      - sbomer
      - fetcher
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

dockers:
  - image_templates:
      - "ghcr.io/zcubbs/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/zcubbs/{{ .ProjectName }}:latest-amd64"
    use: docker
    goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - docker/entrypoint.sh
      - go.mod
      - go.sum
      - scripts/migrate.go
      - migrations/

  - image_templates:
      - "ghcr.io/zcubbs/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/zcubbs/{{ .ProjectName }}:latest-arm64"
    use: docker
    goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile
    skip_push: false
    build_flag_templates:
      - "--platform=linux/arm64"
    extra_files:
      - docker/entrypoint.sh
      - go.mod
      - go.sum
      - scripts/migrate.go
      - migrations/

docker_manifests:
  - name_template: ghcr.io/zcubbs/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/zcubbs/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/zcubbs/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/zcubbs/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/zcubbs/{{ .ProjectName }}:latest-amd64
      - ghcr.io/zcubbs/{{ .ProjectName }}:latest-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^conf:'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - cmd: gpg
    args:
      - --output
      - $signature
      - --detach-sig
      - $artifact
    signature: ${artifact}.sig
    artifacts: none
release:
  github:
    owner: zcubbs
    name: sbomer
  draft: false
  prerelease: auto
  header: |
    ## ({{ .Date }})

    Welcome to this new release!
  footer: |
    ## Thanks!
    Those were the changes on {{ .Tag }}!
  name_template: "{{.Tag}}"
