CREATE TABLE IF NOT EXISTS operations (
    id SERIAL PRIMARY KEY,
    project_id INTEGER NOT NULL,
    operation VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
